# Sleep Health and Lifestyle - EDA

## Introduction
- A dataset containing information on people's sleep will be explored to check if a variety of variables affect one's sleep
- Variables include, gender, age, physical activity level, stress, BMI, etc.

## 1. Discover

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('../data/Sleep_health_and_lifestyle_dataset.csv')
df.columns = df.columns.str.replace(' ', '_')
df.head()

,Person_ID,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Sleep_Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

- renamed columns early since dot-notation may be required during Discover phase

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person_ID                374 non-null    int64
 1   Gender                   374 non-null    str
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    str
 4   Sleep_Duration           374 non-null    float64
 5   Quality_of_Sleep         374 non-null    int64
 6   Physical_Activity_Level  374 non-null    int64
 7   Stress_Level             374 non-null    int64
 8   BMI_Category             374 non-null    str
 9   Blood_Pressure           374 non-null    str
 10  Heart_Rate               374 non-null    int64
 11  Daily_Steps              374 non-null    int64
 12  Sleep_Disorder           155 non-null    str
dtypes: float64(1), int64(7), str(5)
memory usage: 38.1 KB

In [3]:
df['Sleep_Disorder'].unique()

<StringArray>
[nan, 'Sleep Apnea', 'Insomnia']
Length: 3, dtype: str

In [4]:
df['Sleep_Disorder'].value_counts()

Sleep_Disorder
Sleep Apnea    78
Insomnia       77
Name: count, dtype: int64

In [5]:
df['BMI_Category'].unique()

<StringArray>
['Overweight', 'Normal', 'Obese', 'Normal Weight']
Length: 4, dtype: str

In [6]:
df['BMI_Category'].value_counts()

BMI_Category
Normal           195
Overweight       148
Normal Weight     21
Obese             10
Name: count, dtype: int64

## 2. Clean

- After viewing data I changed the missing values in "Sleep Disorder" column to "None" to be more in line with the fact that the individual did not exhibit any specific sleep disorder.

In [7]:
df['Sleep_Disorder'] = df['Sleep_Disorder'].fillna('None')
df.head(20)

,Person_ID,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Sleep_Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
7,8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
8,9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
9,10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
10,11,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,None
11,12,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
12,13,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,None
13,14,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,None
14,15,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,None
15,16,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,None
16,17,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea
17,18,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,Sleep Apnea
18,19,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Insomnia
19,20,Male,30,Doctor,7.6,7,75,6,Normal,120/80,70,8000,None

- Replaces "Normal Weight" to "Normal" to keep consistency

In [8]:
df['BMI_Category'] = df['BMI_Category'].str.replace('Normal Weight', 'Normal')

## 3. Verify

In [9]:
df.columns

Index(['Person_ID', 'Gender', 'Age', 'Occupation', 'Sleep_Duration',
       'Quality_of_Sleep', 'Physical_Activity_Level', 'Stress_Level',
       'BMI_Category', 'Blood_Pressure', 'Heart_Rate', 'Daily_Steps',
       'Sleep_Disorder'],
      dtype='str')

In [10]:
df['Sleep_Disorder'].value_counts()

Sleep_Disorder
None           219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [11]:
df['BMI_Category'].value_counts()
df.head(20)

,Person_ID,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Sleep_Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
7,8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
8,9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
9,10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
10,11,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,None
11,12,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
12,13,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,None
13,14,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,None
14,15,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,None
15,16,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,None
16,17,Female,29,Nurse,6.5,5,40,7,Normal,132/87,80,4000,Sleep Apnea
17,18,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,Sleep Apnea
18,19,Female,29,Nurse,6.5,5,40,7,Normal,132/87,80,4000,Insomnia
19,20,Male,30,Doctor,7.6,7,75,6,Normal,120/80,70,8000,None

## 4. Questions
- Does daily steps affect sleep duration?
- Does daily steps affect quality of sleep?
-

## 5. Analysis

## 6. Conclusion